-- Custom IT skills + aliases seed for HR_Management / ITJob
-- Generated from current Skill + SkillAlias exports.
-- Safe behavior:
-- 1) Reuses existing Skill rows by LOWER(name)
-- 2) Inserts only missing Skill rows
-- 3) Inserts aliases only when no alias exists by LOWER(alias_text)
-- 4) Removes unsafe BI alias that caused false-positive matches from Vietnamese text like "tieu bieu"

ROLLBACK;

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TEMP TABLE tmp_custom_it_skill_seed (
  name TEXT NOT NULL,
  category TEXT,
  source TEXT,
  description TEXT,
  aliases TEXT
) ON COMMIT DROP;

INSERT INTO tmp_custom_it_skill_seed (name, category, source, description, aliases)
VALUES
  ('ReactJS', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: ReactJS', 'ReactJS;React;React.js;React JS;React framework'),
  ('Next.js', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Next.js', 'Next.js;NextJS;Next JS;Next framework'),
  ('Vue.js', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Vue.js', 'Vue.js;VueJS;Vue JS;Vue framework'),
  ('Nuxt.js', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Nuxt.js', 'Nuxt.js;NuxtJS;Nuxt JS'),
  ('Angular', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Angular', 'Angular;Angular framework;Angular 2+'),
  ('Svelte', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Svelte', 'Svelte;SvelteKit;Svelte framework'),
  ('Astro', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Astro', 'Astro;Astro JS;Astro framework'),
  ('jQuery', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: jQuery', 'jQuery'),
  ('HTML5', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: HTML5', 'HTML5;HTML;HTML 5'),
  ('CSS3', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: CSS3', 'CSS3;CSS;CSS 3'),
  ('Sass', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Sass', 'Sass;SCSS;Sass CSS'),
  ('Tailwind CSS', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Tailwind CSS', 'Tailwind CSS;Tailwind;TailwindCSS'),
  ('Bootstrap', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Bootstrap', 'Bootstrap;Bootstrap CSS'),
  ('Material UI', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Material UI', 'Material UI;MUI;Material-UI'),
  ('Chakra UI', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Chakra UI', 'Chakra UI;ChakraUI'),
  ('Ant Design', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Ant Design', 'Ant Design;AntD'),
  ('Redux', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Redux', 'Redux;Redux Toolkit;RTK Query'),
  ('Zustand', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Zustand', 'Zustand;Zustand state management'),
  ('TanStack Query', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: TanStack Query', 'TanStack Query;React Query'),
  ('Vite', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Vite', 'Vite;ViteJS;Vite build tool'),
  ('Webpack', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Webpack', 'Webpack;Webpack bundler'),
  ('Babel', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Babel', 'Babel;Babel JS'),
  ('Storybook', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Storybook', 'Storybook;Storybook UI'),
  ('Micro Frontends', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Micro Frontends', 'Micro Frontends;Microfrontend;Micro Frontend'),
  ('Web Components', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: Web Components', 'Web Components;Custom Elements'),
  ('PWA', 'Frontend', 'CUSTOM_IT_TREND_2026', 'Frontend skill / technology: PWA', 'PWA;Progressive Web App;Progressive Web Apps'),
  ('JavaScript', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: JavaScript', 'JavaScript;JavaScript language;ECMAScript'),
  ('TypeScript', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: TypeScript', 'TypeScript;TypeScript language'),
  ('Node.js', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Node.js', 'Node.js;NodeJS;Node JS;Node runtime'),
  ('NestJS', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: NestJS', 'NestJS;Nest.js;Nest JS;NestJS framework'),
  ('Express.js', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Express.js', 'Express.js;ExpressJS;Express JS;Express framework'),
  ('Fastify', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Fastify', 'Fastify;Fastify framework'),
  ('Java', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Java', 'Java;Java language'),
  ('Spring Boot', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Spring Boot', 'Spring Boot;SpringBoot;Spring Framework;Spring Boot framework'),
  ('Python', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Python', 'Python;Python 3;Python language'),
  ('FastAPI', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: FastAPI', 'FastAPI;Fast API;FastAPI framework'),
  ('Django', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Django', 'Django;Django framework;Django REST Framework;DRF'),
  ('Flask', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Flask', 'Flask;Flask framework'),
  ('Ruby on Rails', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Ruby on Rails', 'Ruby on Rails;Rails;Ruby Rails'),
  ('PHP', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: PHP', 'PHP;PHP language'),
  ('Laravel', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Laravel', 'Laravel;Laravel framework'),
  ('Symfony', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Symfony', 'Symfony;Symfony framework'),
  ('ASP.NET Core', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: ASP.NET Core', 'ASP.NET Core;ASP Net Core;Dotnet Core'),
  ('.NET', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: .NET', '.NET;DotNet;.NET framework;.NET Core'),
  ('C#', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: C#', 'C#;C Sharp;CSharp;C# language'),
  ('Kotlin', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Kotlin', 'Kotlin;Kotlin language'),
  ('Scala', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Scala', 'Scala;Scala language'),
  ('Rust', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Rust', 'Rust;Rust language'),
  ('Golang', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Golang', 'Golang;Go language'),
  ('Elixir', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Elixir', 'Elixir;Elixir language'),
  ('Phoenix Framework', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Phoenix Framework', 'Phoenix Framework;Phoenix'),
  ('GraphQL', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: GraphQL', 'GraphQL;GraphQL API;Graph QL'),
  ('REST API', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: REST API', 'REST API;RESTful API;REST service'),
  ('gRPC', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: gRPC', 'gRPC;gRPC API;Remote Procedure Call'),
  ('WebSocket', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: WebSocket', 'WebSocket;WebSockets;Web Socket'),
  ('OAuth 2.0', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: OAuth 2.0', 'OAuth 2.0;OAuth2;OAuth 2'),
  ('OpenID Connect', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: OpenID Connect', 'OpenID Connect;OIDC'),
  ('JWT', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: JWT', 'JWT;JSON Web Token;JWT auth'),
  ('Microservices', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Microservices', 'Microservices;Microservice Architecture;Micro services'),
  ('Event-driven Architecture', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Event-driven Architecture', 'Event-driven Architecture;Event driven architecture;EDA'),
  ('Domain-driven Design', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Domain-driven Design', 'Domain-driven Design;DDD;Domain Driven Design'),
  ('Clean Architecture', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: Clean Architecture', 'Clean Architecture'),
  ('CQRS', 'Backend', 'CUSTOM_IT_TREND_2026', 'Backend skill / technology: CQRS', 'CQRS;Command Query Responsibility Segregation'),
  ('PostgreSQL', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: PostgreSQL', 'PostgreSQL;Postgres;Postgre SQL'),
  ('MySQL', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: MySQL', 'MySQL;My SQL'),
  ('MariaDB', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: MariaDB', 'MariaDB;Maria DB'),
  ('SQL Server', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: SQL Server', 'SQL Server;MSSQL;MS SQL;Microsoft SQL Server'),
  ('SQLite', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: SQLite', 'SQLite;SQLite database'),
  ('Oracle Database', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: Oracle Database', 'Oracle Database;Oracle DB'),
  ('MongoDB', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: MongoDB', 'MongoDB;Mongo DB;Mongo'),
  ('Redis', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: Redis', 'Redis;Redis cache'),
  ('Elasticsearch', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: Elasticsearch', 'Elasticsearch;Elastic Search;Elastic'),
  ('OpenSearch', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: OpenSearch', 'OpenSearch;Open Search'),
  ('Cassandra', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: Cassandra', 'Cassandra;Apache Cassandra'),
  ('DynamoDB', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: DynamoDB', 'DynamoDB;Amazon DynamoDB;AWS DynamoDB'),
  ('Firebase Firestore', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: Firebase Firestore', 'Firebase Firestore;Firestore;Cloud Firestore'),
  ('Supabase', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: Supabase', 'Supabase;Supabase database'),
  ('Prisma ORM', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: Prisma ORM', 'Prisma ORM;Prisma;Prisma Client'),
  ('TypeORM', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: TypeORM', 'TypeORM;Type ORM'),
  ('Sequelize', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: Sequelize', 'Sequelize;Sequelize ORM'),
  ('Mongoose', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: Mongoose', 'Mongoose;Mongoose ODM'),
  ('SQLAlchemy', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: SQLAlchemy', 'SQLAlchemy;SQL Alchemy'),
  ('Alembic', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: Alembic', 'Alembic;Alembic migration'),
  ('Database Indexing', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: Database Indexing', 'Database Indexing;DB indexing;SQL indexing'),
  ('Query Optimization', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: Query Optimization', 'Query Optimization;SQL optimization;query tuning'),
  ('Data Modeling', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: Data Modeling', 'Data Modeling;database modeling;data modelling'),
  ('ETL', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: ETL', 'ETL;Extract Transform Load;ETL pipeline'),
  ('ELT', 'Database', 'CUSTOM_IT_TREND_2026', 'Database skill / technology: ELT', 'ELT;Extract Load Transform;ELT pipeline'),
  ('Linux', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Linux', 'Linux;Linux server;Ubuntu;CentOS;Debian;Rocky Linux'),
  ('Bash', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Bash', 'Bash;Shell scripting;Bash scripting;Shell script'),
  ('Docker', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Docker', 'Docker;Docker container;containerization;containerized services'),
  ('Docker Compose', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Docker Compose', 'Docker Compose;docker-compose'),
  ('Kubernetes', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Kubernetes', 'Kubernetes;K8s;Kubernetes cluster;container orchestration'),
  ('Helm', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Helm', 'Helm;Helm chart;Helm charts'),
  ('Kustomize', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Kustomize', 'Kustomize;Kustomize Kubernetes'),
  ('Terraform', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Terraform', 'Terraform;Terraform IaC;HashiCorp Terraform'),
  ('Pulumi', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Pulumi', 'Pulumi;Pulumi IaC'),
  ('Ansible', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Ansible', 'Ansible;Ansible automation'),
  ('Jenkins', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Jenkins', 'Jenkins;Jenkins CI;Jenkins pipeline'),
  ('GitHub Actions', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: GitHub Actions', 'GitHub Actions;Git Hub Actions;GitHub workflow'),
  ('GitLab CI/CD', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: GitLab CI/CD', 'GitLab CI/CD;GitLab CI;GitLab CI CD;Git Lab CI;GitLab pipeline'),
  ('CI/CD', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: CI/CD', 'CI/CD;CI CD;CICD;Continuous Integration;Continuous Deployment;Continuous Delivery;build test deploy;build-test-deploy'),
  ('Argo CD', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Argo CD', 'Argo CD;ArgoCD;GitOps deployment'),
  ('FluxCD', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: FluxCD', 'FluxCD;Flux CD;GitOps Flux'),
  ('GitOps', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: GitOps', 'GitOps;Git Ops;GitOps workflow'),
  ('Nginx', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Nginx', 'Nginx;reverse proxy'),
  ('Apache HTTP Server', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Apache HTTP Server', 'Apache HTTP Server;Apache server;httpd'),
  ('HAProxy', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: HAProxy', 'HAProxy;HA Proxy'),
  ('Traefik', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Traefik', 'Traefik;Traefik proxy'),
  ('Prometheus', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Prometheus', 'Prometheus;Prometheus monitoring;PromQL'),
  ('Grafana', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Grafana', 'Grafana;Grafana dashboard;Grafana monitoring'),
  ('Loki', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Loki', 'Loki;Grafana Loki;Loki logs'),
  ('ELK Stack', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: ELK Stack', 'ELK Stack;Elastic Stack;Elasticsearch Logstash Kibana;ELK'),
  ('OpenTelemetry', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: OpenTelemetry', 'OpenTelemetry;Open Telemetry;OTel;distributed tracing'),
  ('Jaeger', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Jaeger', 'Jaeger;Jaeger tracing'),
  ('Kibana', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Kibana', 'Kibana;Kibana dashboard'),
  ('Datadog', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Datadog', 'Datadog;DataDog monitoring'),
  ('New Relic', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: New Relic', 'New Relic;NewRelic;New Relic APM'),
  ('Sentry', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Sentry', 'Sentry;Sentry error tracking'),
  ('Cloud Services', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Cloud Services', 'Cloud Services;Cloud service;Cloud operations;Cloud computing'),
  ('AWS', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: AWS', 'AWS;Amazon Web Services;AWS cloud'),
  ('Azure', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Azure', 'Azure;Microsoft Azure;Azure cloud'),
  ('Google Cloud', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Google Cloud', 'Google Cloud;GCP;Google Cloud Platform'),
  ('Cloudflare', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Cloudflare', 'Cloudflare;Cloudflare Workers;Cloudflare CDN'),
  ('Vercel', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Vercel', 'Vercel;Vercel platform'),
  ('Netlify', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Netlify', 'Netlify;Netlify platform'),
  ('Heroku', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Heroku', 'Heroku;Heroku platform'),
  ('DigitalOcean', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: DigitalOcean', 'DigitalOcean;Digital Ocean'),
  ('Firebase', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Firebase', 'Firebase;Firebase platform'),
  ('AWS Lambda', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: AWS Lambda', 'AWS Lambda;Lambda;Amazon Lambda;serverless lambda'),
  ('Serverless Framework', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Serverless Framework', 'Serverless Framework;Serverless'),
  ('AWS ECS', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: AWS ECS', 'AWS ECS;Elastic Container Service;Amazon ECS'),
  ('AWS EKS', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: AWS EKS', 'AWS EKS;Elastic Kubernetes Service;Amazon EKS'),
  ('AWS S3', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: AWS S3', 'AWS S3;Amazon S3;S3 storage'),
  ('AWS EC2', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: AWS EC2', 'AWS EC2;Amazon EC2;EC2 instance'),
  ('AWS RDS', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: AWS RDS', 'AWS RDS;Amazon RDS;RDS database'),
  ('Azure DevOps', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Azure DevOps', 'Azure DevOps;Azure Pipelines'),
  ('Monitoring', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Monitoring', 'Monitoring;alerting;observability;system monitoring;canh bao tai nguyen'),
  ('Site Reliability Engineering', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Site Reliability Engineering', 'Site Reliability Engineering;SRE;Reliability engineering'),
  ('Incident Response', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Incident Response', 'Incident Response;incident management;production incident'),
  ('Infrastructure as Code', 'DevOps/Cloud', 'CUSTOM_IT_TREND_2026', 'DevOps/Cloud skill / technology: Infrastructure as Code', 'Infrastructure as Code;IaC'),
  ('Machine Learning', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Machine Learning', 'Machine Learning;machine learning models;ML engineering'),
  ('Deep Learning', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Deep Learning', 'Deep Learning;neural networks;DL models'),
  ('Generative AI', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Generative AI', 'Generative AI;GenAI;AI generation'),
  ('Large Language Models', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Large Language Models', 'Large Language Models;LLM;LLMs;Large Language Model'),
  ('Retrieval-Augmented Generation', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Retrieval-Augmented Generation', 'Retrieval-Augmented Generation;RAG;Retrieval Augmented Generation'),
  ('Prompt Engineering', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Prompt Engineering', 'Prompt Engineering;prompt design'),
  ('Fine-tuning', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Fine-tuning', 'Fine-tuning;model fine tuning;fine tuning'),
  ('Embeddings', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Embeddings', 'Embeddings;text embeddings;embedding models;vector embeddings'),
  ('Vector Database', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Vector Database', 'Vector Database;vector DB;vector search;semantic search'),
  ('Pinecone', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Pinecone', 'Pinecone;Pinecone vector database'),
  ('Weaviate', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Weaviate', 'Weaviate;Weaviate vector database'),
  ('Milvus', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Milvus', 'Milvus;Milvus vector database'),
  ('Qdrant', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Qdrant', 'Qdrant;Qdrant vector database'),
  ('ChromaDB', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: ChromaDB', 'ChromaDB;Chroma DB;Chroma database'),
  ('FAISS', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: FAISS', 'FAISS;Facebook AI Similarity Search;FAISS index'),
  ('LangChain', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: LangChain', 'LangChain;LangChain framework'),
  ('LangGraph', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: LangGraph', 'LangGraph;LangGraph agents'),
  ('LlamaIndex', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: LlamaIndex', 'LlamaIndex;Llama Index;GPT Index'),
  ('OpenAI API', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: OpenAI API', 'OpenAI API;OpenAI SDK'),
  ('Anthropic Claude API', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Anthropic Claude API', 'Anthropic Claude API;Claude API;Anthropic API'),
  ('Hugging Face Transformers', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Hugging Face Transformers', 'Hugging Face Transformers;Transformers;HuggingFace Transformers;Hugging Face'),
  ('PyTorch', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: PyTorch', 'PyTorch;Torch;PyTorch framework'),
  ('TensorFlow', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: TensorFlow', 'TensorFlow;Tensor Flow;TensorFlow framework'),
  ('Keras', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Keras', 'Keras;Keras framework'),
  ('Scikit-learn', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Scikit-learn', 'Scikit-learn;sklearn;Scikit learn'),
  ('Pandas', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Pandas', 'Pandas;Pandas dataframe'),
  ('NumPy', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: NumPy', 'NumPy'),
  ('SciPy', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: SciPy', 'SciPy'),
  ('Matplotlib', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Matplotlib', 'Matplotlib;Matplotlib plotting'),
  ('Jupyter Notebook', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Jupyter Notebook', 'Jupyter Notebook;Jupyter;JupyterLab'),
  ('Apache Spark', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Apache Spark', 'Apache Spark;Spark;PySpark'),
  ('Databricks', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Databricks', 'Databricks;Databricks platform'),
  ('Airflow', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Airflow', 'Airflow;Apache Airflow;Airflow DAG'),
  ('dbt', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: dbt', 'dbt;dbt core;data build tool'),
  ('Snowflake', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Snowflake', 'Snowflake;Snowflake data warehouse'),
  ('BigQuery', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: BigQuery', 'BigQuery;Google BigQuery'),
  ('Redshift', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Redshift', 'Redshift;Amazon Redshift;AWS Redshift'),
  ('Power BI', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Power BI', 'Power BI;PowerBI'),
  ('Tableau', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Tableau', 'Tableau;Tableau BI'),
  ('Looker', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Looker', 'Looker;Looker Studio;Google Looker'),
  ('Data Engineering', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Data Engineering', 'Data Engineering;data engineer;data pipelines'),
  ('Data Analysis', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Data Analysis', 'Data Analysis;data analytics;data analyst'),
  ('Business Intelligence', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Business Intelligence', 'Business Intelligence;Power BI;BI analyst;dashboard reporting'),
  ('MLOps', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: MLOps', 'MLOps;ML Ops;Machine Learning Operations'),
  ('MLflow', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: MLflow', 'MLflow;MLflow tracking'),
  ('Kubeflow', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Kubeflow', 'Kubeflow'),
  ('Model Deployment', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Model Deployment', 'Model Deployment;ML model deployment;model serving'),
  ('Feature Engineering', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Feature Engineering', 'Feature Engineering;feature extraction'),
  ('Natural Language Processing', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Natural Language Processing', 'Natural Language Processing;NLP'),
  ('Computer Vision', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: Computer Vision', 'Computer Vision;CV models;image recognition'),
  ('OCR', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: OCR', 'OCR;Optical Character Recognition'),
  ('A/B Testing', 'AI/Data', 'CUSTOM_IT_TREND_2026', 'AI/Data skill / technology: A/B Testing', 'A/B Testing;AB testing;experiment testing'),
  ('Unit Testing', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: Unit Testing', 'Unit Testing;unit tests'),
  ('Integration Testing', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: Integration Testing', 'Integration Testing;integration tests'),
  ('End-to-End Testing', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: End-to-End Testing', 'End-to-End Testing;E2E testing;end to end testing'),
  ('Test Automation', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: Test Automation', 'Test Automation;automation testing;automated testing'),
  ('Jest', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: Jest', 'Jest;Jest testing'),
  ('Vitest', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: Vitest', 'Vitest;Vitest testing'),
  ('Cypress', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: Cypress', 'Cypress;Cypress testing'),
  ('Playwright', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: Playwright', 'Playwright;Playwright testing'),
  ('Selenium', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: Selenium', 'Selenium;Selenium WebDriver'),
  ('Postman', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: Postman', 'Postman;Postman API testing'),
  ('Swagger', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: Swagger', 'Swagger;OpenAPI;Swagger UI'),
  ('API Testing', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: API Testing', 'API Testing;API test'),
  ('Load Testing', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: Load Testing', 'Load Testing;performance testing;stress testing'),
  ('JMeter', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: JMeter', 'JMeter;Apache JMeter'),
  ('k6', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: k6', 'Grafana k6;k6 load testing'),
  ('SonarQube', 'Testing/QA', 'CUSTOM_IT_TREND_2026', 'Testing/QA skill / technology: SonarQube', 'SonarQube;Sonar Qube;code quality'),
  ('Flutter', 'Mobile', 'CUSTOM_IT_TREND_2026', 'Mobile skill / technology: Flutter', 'Flutter;Flutter framework;Dart Flutter'),
  ('Dart', 'Mobile', 'CUSTOM_IT_TREND_2026', 'Mobile skill / technology: Dart', 'Dart;Dart language'),
  ('React Native', 'Mobile', 'CUSTOM_IT_TREND_2026', 'Mobile skill / technology: React Native', 'React Native;ReactNative'),
  ('Android', 'Mobile', 'CUSTOM_IT_TREND_2026', 'Mobile skill / technology: Android', 'Android;Android development'),
  ('iOS', 'Mobile', 'CUSTOM_IT_TREND_2026', 'Mobile skill / technology: iOS', 'iOS;iOS development'),
  ('Swift', 'Mobile', 'CUSTOM_IT_TREND_2026', 'Mobile skill / technology: Swift', 'Swift;Swift language'),
  ('Kotlin Android', 'Mobile', 'CUSTOM_IT_TREND_2026', 'Mobile skill / technology: Kotlin Android', 'Kotlin Android;Kotlin mobile;Android Kotlin'),
  ('Jetpack Compose', 'Mobile', 'CUSTOM_IT_TREND_2026', 'Mobile skill / technology: Jetpack Compose', 'Jetpack Compose;Compose Android'),
  ('SwiftUI', 'Mobile', 'CUSTOM_IT_TREND_2026', 'Mobile skill / technology: SwiftUI', 'SwiftUI;Swift UI'),
  ('Firebase Cloud Messaging', 'Mobile', 'CUSTOM_IT_TREND_2026', 'Mobile skill / technology: Firebase Cloud Messaging', 'Firebase Cloud Messaging;FCM;Firebase messaging'),
  ('Mobile App Development', 'Mobile', 'CUSTOM_IT_TREND_2026', 'Mobile skill / technology: Mobile App Development', 'Mobile App Development;mobile development;mobile apps'),
  ('Cybersecurity', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: Cybersecurity', 'Cybersecurity;cyber security;information security'),
  ('OWASP Top 10', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: OWASP Top 10', 'OWASP Top 10;OWASP;OWASP Top Ten'),
  ('Web Application Security', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: Web Application Security', 'Web Application Security;web security;application security'),
  ('Penetration Testing', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: Penetration Testing', 'Penetration Testing;pentest;penetration test'),
  ('Vulnerability Assessment', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: Vulnerability Assessment', 'Vulnerability Assessment;vulnerability scanning'),
  ('Static Application Security Testing', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: Static Application Security Testing', 'Static Application Security Testing;SAST;static security testing'),
  ('Dynamic Application Security Testing', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: Dynamic Application Security Testing', 'Dynamic Application Security Testing;DAST;dynamic security testing'),
  ('Software Composition Analysis', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: Software Composition Analysis', 'Software Composition Analysis;SCA;dependency scanning'),
  ('Secrets Management', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: Secrets Management', 'Secrets Management;secret management;vault'),
  ('HashiCorp Vault', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: HashiCorp Vault', 'HashiCorp Vault;Vault'),
  ('IAM', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: IAM', 'IAM;Identity and Access Management;access management'),
  ('Zero Trust', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: Zero Trust', 'Zero Trust;zero trust security'),
  ('SOC 2', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: SOC 2', 'SOC 2;SOC2;SOC 2 compliance'),
  ('ISO 27001', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: ISO 27001', 'ISO 27001;ISO27001'),
  ('SIEM', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: SIEM', 'SIEM;security information event management'),
  ('WAF', 'Security', 'CUSTOM_IT_TREND_2026', 'Security skill / technology: WAF', 'WAF;Web Application Firewall;application firewall'),
  ('Agile Development', 'Software Engineering', 'CUSTOM_IT_TREND_2026', 'Software Engineering skill / technology: Agile Development', 'Agile Development;Agile;Scrum;Agile methodology'),
  ('Scrum', 'Software Engineering', 'CUSTOM_IT_TREND_2026', 'Software Engineering skill / technology: Scrum', 'Scrum;Scrum framework;Scrum methodology'),
  ('Kanban', 'Software Engineering', 'CUSTOM_IT_TREND_2026', 'Software Engineering skill / technology: Kanban', 'Kanban;Kanban board'),
  ('Jira', 'Software Engineering', 'CUSTOM_IT_TREND_2026', 'Software Engineering skill / technology: Jira', 'Jira;Atlassian Jira'),
  ('Confluence', 'Software Engineering', 'CUSTOM_IT_TREND_2026', 'Software Engineering skill / technology: Confluence', 'Confluence;Atlassian Confluence'),
  ('Git', 'Software Engineering', 'CUSTOM_IT_TREND_2026', 'Software Engineering skill / technology: Git', 'Git;version control;Git version control'),
  ('GitHub', 'Software Engineering', 'CUSTOM_IT_TREND_2026', 'Software Engineering skill / technology: GitHub', 'GitHub;Git Hub'),
  ('GitLab', 'Software Engineering', 'CUSTOM_IT_TREND_2026', 'Software Engineering skill / technology: GitLab', 'GitLab;Git Lab'),
  ('Bitbucket', 'Software Engineering', 'CUSTOM_IT_TREND_2026', 'Software Engineering skill / technology: Bitbucket', 'Bitbucket;Bit bucket'),
  ('Code Review', 'Software Engineering', 'CUSTOM_IT_TREND_2026', 'Software Engineering skill / technology: Code Review', 'Code Review;pull request review;merge request review'),
  ('Technical Documentation', 'Software Engineering', 'CUSTOM_IT_TREND_2026', 'Software Engineering skill / technology: Technical Documentation', 'Technical Documentation;documentation;technical docs'),
  ('System Design', 'Software Engineering', 'CUSTOM_IT_TREND_2026', 'Software Engineering skill / technology: System Design', 'System Design;software architecture;architecture design'),
  ('API Design', 'Software Engineering', 'CUSTOM_IT_TREND_2026', 'Software Engineering skill / technology: API Design', 'API Design;API architecture;REST design'),
  ('UML', 'Software Engineering', 'CUSTOM_IT_TREND_2026', 'Software Engineering skill / technology: UML', 'UML;Unified Modeling Language')
;

-- Insert missing skills only. If ESCO already has a skill with the same name, keep the old row.
INSERT INTO "Skill" (
  id,
  name,
  is_active,
  source,
  description,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  TRIM(t.name),
  TRUE,
  COALESCE(NULLIF(TRIM(t.source), ''), 'CUSTOM_IT_TREND_2026'),
  NULLIF(TRIM(t.description), ''),
  NOW(),
  NOW()
FROM tmp_custom_it_skill_seed t
WHERE NOT EXISTS (
  SELECT 1
  FROM "Skill" s
  WHERE LOWER(TRIM(s.name)) = LOWER(TRIM(t.name))
);

-- Add aliases for both existing ESCO skills and newly inserted custom skills.
-- This is the important part for CV/JD matching.
INSERT INTO "SkillAlias" (
  id,
  skill_id,
  alias_text,
  created_at
)
SELECT DISTINCT ON (LOWER(TRIM(a.alias_text)))
  gen_random_uuid(),
  s.id,
  TRIM(a.alias_text),
  NOW()
FROM tmp_custom_it_skill_seed t
JOIN "Skill" s
  ON LOWER(TRIM(s.name)) = LOWER(TRIM(t.name))
CROSS JOIN LATERAL unnest(string_to_array(COALESCE(t.aliases, ''), ';')) AS a(alias_text)
WHERE
  TRIM(a.alias_text) <> ''
  AND LENGTH(REGEXP_REPLACE(TRIM(a.alias_text), '[^A-Za-z0-9+#.]', '', 'g')) >= 3
ORDER BY
  LOWER(TRIM(a.alias_text)),
  LOWER(TRIM(t.name))
ON CONFLICT (alias_text) DO NOTHING;

-- Avoid dangerous short alias that matched Vietnamese broken text: "tieu bieu" -> "bi".
DELETE FROM "SkillAlias"
WHERE LOWER(TRIM(alias_text)) = 'bi';

COMMIT;

-- Verification queries:
-- SELECT COUNT(*) FROM "Skill";
-- SELECT COUNT(*) FROM "SkillAlias";
-- SELECT id, name FROM "Skill" WHERE LOWER(name) IN ('docker', 'kubernetes', 'ci/cd', 'linux', 'bash', 'cloud services', 'monitoring');
-- SELECT s.name, sa.alias_text FROM "SkillAlias" sa JOIN "Skill" s ON s.id = sa.skill_id WHERE LOWER(s.name) IN ('docker', 'kubernetes', 'ci/cd', 'linux', 'bash', 'cloud services', 'monitoring') ORDER BY s.name, sa.alias_text;
